version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: musinsa1234
      MYSQL_DATABASE: musinsa
      MYSQL_USER: musinsa-admin-api
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql